# -*- coding: utf-8 -*-
"""DataGovernance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lid5khkDswjKNb1WoOcFeClhb787_hhu
"""

!pip install pymysql

!pip install SQLAlchemy

import pymysql

# Connect to your RDS MySQL instance
connection = pymysql.connect(
    host='demo-rds-mysql-db.csb002k2ask1.us-east-1.rds.amazonaws.com',  # ← replace with your RDS host
    user='admin',                            # ← replace with your username
    password='Shmuokh001*',                # ← replace with your password
    database='demo_db',                # ← replace with your DB name
    port=3306
)

print("✅ Connected to RDS MySQL")

# SQL code for email format validation triggers
trigger_code = """
CREATE TRIGGER validate_email_before_insert
BEFORE INSERT ON users
FOR EACH ROW
BEGIN
  IF NEW.email NOT REGEXP '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$' THEN
    SIGNAL SQLSTATE '45000'
    SET MESSAGE_TEXT = '❌ Invalid email format on INSERT!';
  END IF;
END //

CREATE TRIGGER validate_email_before_update
BEFORE UPDATE ON users
FOR EACH ROW
BEGIN
  IF NEW.email NOT REGEXP '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$' THEN
    SIGNAL SQLSTATE '45000'
    SET MESSAGE_TEXT = '❌ Invalid email format on UPDATE!';
  END IF;
END //
"""

# Execute each SQL statement separately
with connection.cursor() as cursor:
    for statement in trigger_code.split('//'):
        if statement.strip():
            cursor.execute(statement)

connection.commit()
connection.close()
print("✅ Triggers created successfully.")

try:
    connection = pymysql.connect(
        host='demo-rds-mysql-db.csb002k2ask1.us-east-1.rds.amazonaws.com',
        user='admin',
        password='Shmuokh001*',
        database='demo_db',
        port=3306
    )

    with connection.cursor() as cursor:
        cursor.execute("""
            INSERT INTO users (id, email, student_id)
            VALUES (9999, 'wrong@@email', 'Stud9999')
        """)
    connection.commit()
    print("❌ This should NOT be printed – trigger failed to block bad email!")

except Exception as e:
    print("✅ Trigger blocked the insert as expected!")
    print("MySQL Error Message:", e)

finally:
    connection.close()

try:
    connection = pymysql.connect(
        host='demo-rds-mysql-db.csb002k2ask1.us-east-1.rds.amazonaws.com',
        user='admin',
        password='Shmuokh001*',
        database='demo_db',
        port=3306
    )

    with connection.cursor() as cursor:
        cursor.execute("""
            INSERT INTO users (id, email, student_id)
            VALUES (10000, 'correct.email@example.com', 'Stud10000')
        """)
    connection.commit()
    print("✅ Correct email inserted successfully.")

except Exception as e:
    print("❌ Failed to insert valid email.")
    print("MySQL Error Message:", e)

finally:
    connection.close()