# -*- coding: utf-8 -*-
"""Data Quality.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zyA_defln6KGucIlQT1X_2TkvnXa1W_J

# Data Quality for Capston Project - Stage 2 ⭐
- users
- cohorts
- cohort_enrollments
- cohort_courses
- assiements
- Cohort_Assignment
- cohort_course_enrollments
- Quizzes
- attendanc
- Change_Requests
- Student_Status
- Change_Requests

# Install libraries
"""

!pip install SQLAlchemy

!pip install PyMySQL

"""# Import library"""

from sqlalchemy import create_engine
from sqlalchemy import text
import pandas as pd
import numpy as np

"""# Make Connection"""

ENDPOINT = "raw-data.csb002k2ask1.us-east-1.rds.amazonaws.com"
PORT = "3306"
USERNAME = "admin"
PASSWORD = "Shmuokh001*"
DATABASENAME = "raw_data"

engine = create_engine(f"mysql+pymysql://{USERNAME}:{PASSWORD}@{ENDPOINT}:{PORT}/{DATABASENAME}")

"""# Data Quality Dimensions
1. Completeness: Are all required values present?

2. Uniqueness: Are there duplicate rows or duplicate IDs?

3. imeliness: Is the data up-to-date and relevant?

4. Validity: Do values follow the expected format and range?

5. Accuracy: Do values represent real-world entities correctly?

6. Consistency: Are values consistent across records and sources?

# users
"""

query = f"SELECT * FROM users"
users_df = pd.read_sql(query, engine)
users_df.head()

import pandas as pd
from sqlalchemy import create_engine
import pymysql

# بيانات الاتصال
ENDPOINT = "raw-data.csb002k2ask1.us-east-1.rds.amazonaws.com"
PORT = "3306"
USERNAME = "admin"
PASSWORD = "Shmuokh001*"
DATABASENAME = "raw_data"

# الاتصال
engine = create_engine(f"mysql+pymysql://{USERNAME}:{PASSWORD}@{ENDPOINT}:{PORT}/{DATABASENAME}")

# قراءة البيانات
df = pd.read_sql("SELECT * FROM attendance", engine)
total_rows = len(df)

# تحويل تاريخ الحضور إلى datetime
if 'attendance_date' in df.columns:
    df['attendance_date'] = pd.to_datetime(df['attendance_date'], errors='coerce')

# حساب معايير الجودة
results = {
    "completeness_pct": df.notnull().sum().sum() / (df.shape[0] * df.shape[1]) * 100,
    "uniqueness_pct": df.drop_duplicates().shape[0] / df.shape[0] * 100,
    "timeliness_pct": df['attendance_date'].ge(pd.Timestamp.today() - pd.Timedelta(days=30)).mean() * 100 if 'attendance_date' in df.columns else None,
    "validity_pct": df['attendance_status'].isin(['P', 'X', 'E', 'L']).mean() * 100 if 'attendance_status' in df.columns else None,
    "accuracy_pct": df['attendance_date'].le(pd.Timestamp.today()).mean() * 100 if 'attendance_date' in df.columns else None,
    "consistency_pct": df.groupby(['StudentID', 'Final_Cohort'])['level'].nunique().le(1).mean() * 100 if set(['StudentID', 'Final_Cohort', 'level']).issubset(df.columns) else None
}

# عرض النتائج
results_df = pd.DataFrame([results])
print(results_df)

query = f"SELECT * FROM attendance"
enrollments_df = pd.read_sql(query, engine)
enrollments_df.head()



import pandas as pd
from sqlalchemy import create_engine
import pymysql
import re

# ⚙️ إعداد الاتصال بقاعدة البيانات
ENDPOINT = "raw-data.csb002k2ask1.us-east-1.rds.amazonaws.com"
PORT = "3306"
USERNAME = "admin"
PASSWORD = "Shmuokh001*"
DATABASENAME = "raw_data"

# إنشاء الاتصال باستخدام SQLAlchemy
engine = create_engine(f"mysql+pymysql://{USERNAME}:{PASSWORD}@{ENDPOINT}:{PORT}/{DATABASENAME}")

# ✅ تحميل البيانات من الجدول (يرجى تحديد اسم الجدول الصحيح)
TABLE_NAME = "attendance"  # ✏️ عدل الاسم حسب الحاجة
df = pd.read_sql(f"SELECT * FROM {TABLE_NAME}", engine)

# ⚙️ تهيئة تقرير الجودة
dq_report = {}

# ✅ 1. Completeness - نسبة القيم غير المفقودة
total_cells = df.size
non_missing_cells = df.notnull().sum().sum()
completeness_pct = (non_missing_cells / total_cells) * 100
dq_report["Completeness (overall)"] = f"{completeness_pct:.2f}%"

# ✅ 2. Uniqueness - الصفوف المميزة بالكامل
unique_rows = df.drop_duplicates().shape[0]
uniqueness_pct = (unique_rows / len(df)) * 100
dq_report["Uniqueness (all rows)"] = f"{uniqueness_pct:.2f}%"

# ✅ 3. Timeliness - تاريخ الحضور خلال آخر 30 يوم
if 'attendance_date' in df.columns:
    df['attendance_date'] = pd.to_datetime(df['attendance_date'], errors='coerce')
    recent_dates_pct = df['attendance_date'].ge(pd.Timestamp.today() - pd.Timedelta(days=30)).mean() * 100
    dq_report["Timeliness (last 30 days)"] = f"{recent_dates_pct:.2f}%"
else:
    dq_report["Timeliness (last 30 days)"] = "Column 'attendance_date' not found"

# ✅ 4. Validity - حالة الحضور (P, X, E, L)
if 'attendance_data' in df.columns:
    valid_status = df['attendance_data'].isin(['P', 'X', 'E', 'L'])
    validity_pct = valid_status.mean() * 100
    dq_report["Validity (attendance_data)"] = f"{validity_pct:.2f}%"
else:
    dq_report["Validity (attendance_data)"] = "Column 'attendance_data' not found"

# ✅ 5. Accuracy - أن يكون التاريخ ≤ اليوم الحالي
if 'attendance_date' in df.columns:
    accurate_dates_pct = df['attendance_date'].le(pd.Timestamp.today()).mean() * 100
    dq_report["Accuracy (attendance_date <= today)"] = f"{accurate_dates_pct:.2f}%"

# ✅ 6. Consistency - نفس StudentID مع Final_Cohort له مستوى واحد فقط
if set(['StudentID', 'Final_Cohort', 'level']).issubset(df.columns):
    consistency_check = df.groupby(['StudentID', 'Final_Cohort'])['level'].nunique().le(1)
    consistency_pct = consistency_check.mean() * 100
    dq_report["Consistency (level by StudentID & Cohort)"] = f"{consistency_pct:.2f}%"
else:
    dq_report["Consistency (level by StudentID & Cohort)"] = "Required columns not found"

# ✅ طباعة تقرير الجودة
print("\n📊 Data Quality Report (attendance):")
for dimension, result in dq_report.items():
    print(f"- {dimension}: {result}")

# ✅ تحويل التقرير إلى DataFrame وحفظه
data_quality_report = pd.DataFrame(
    list(dq_report.items()),
    columns=["Dimension", "Percentage"]
)

data_quality_report.to_csv('attendance_data_quality_report.csv', index=False)
print("\n📁 ✅ تم حفظ التقرير في ملف: attendance_data_quality_report.csv")

results_df.to_csv('attendance_report.csv', index=False)

import pandas as pd
from sqlalchemy import create_engine
import pymysql

# 🛠️ معلومات الاتصال بقاعدة البيانات
ENDPOINT = "raw-data.csb002k2ask1.us-east-1.rds.amazonaws.com"
PORT = "3306"
USERNAME = "admin"
PASSWORD = "Shmuokh001*"
DATABASENAME = "raw_data"

# ⚙️ إنشاء الاتصال
engine = create_engine(f"mysql+pymysql://{USERNAME}:{PASSWORD}@{ENDPOINT}:{PORT}/{DATABASENAME}")

# 📥 قراءة البيانات من جدول attendance
df = pd.read_sql("SELECT * FROM attendance", engine)

# 🕒 تحويل تاريخ الحضور إلى datetime إن وجد
if 'attendance_date' in df.columns:
    df['attendance_date'] = pd.to_datetime(df['attendance_date'], errors='coerce')

# ✅ 1. Completeness
missing_summary = df.isnull().sum()
completeness_result = "Warning ⚠️" if missing_summary.sum() > 0 else "Pass ✅"
completeness_details = f"Missing values found in {missing_summary[missing_summary > 0].count()} columns"

# ✅ 2. Uniqueness
duplicate_rows = df.duplicated().sum()
duplicate_ids = df['StudentID'].duplicated().sum() if 'StudentID' in df.columns else 0
uniqueness_result = "Fail ❌" if duplicate_ids > 0 else "Pass ✅"
uniqueness_details = f"Duplicate rows: {duplicate_rows}, Duplicate Student IDs: {duplicate_ids}"

# ✅ 3. Consistency
if set(['StudentID', 'Final_Cohort', 'level']).issubset(df.columns):
    level_consistent = df.groupby(['StudentID', 'Final_Cohort'])['level'].nunique().le(1).all()
    consistency_result = "Pass ✅" if level_consistent else "Fail ❌"
    consistency_details = f"Level consistency within StudentID/Cohort: {level_consistent}"
else:
    consistency_result = "N/A"
    consistency_details = "Required columns for consistency not found"

# ✅ 4. Timeliness
current_date = pd.Timestamp.now()
if 'attendance_date' in df.columns:
    recent_data_pct = df['attendance_date'].dropna().ge(current_date - pd.Timedelta(days=30)).mean() * 100
    future_dates_count = df['attendance_date'].dropna().gt(current_date).sum()
    timeliness_result = "Warning ⚠️" if recent_data_pct < 100 else "Pass ✅"
    timeliness_details = f"{recent_data_pct:.1f}% of records from last 30 days"
else:
    timeliness_result = "N/A"
    timeliness_details = "Column 'attendance_date' not found"

# ✅ 5. Accuracy (no future dates)
if 'attendance_date' in df.columns:
    accuracy_result = "Fail ❌" if future_dates_count > 0 else "Pass ✅"
    accuracy_details = f"Found {future_dates_count} future dates"
else:
    accuracy_result = "N/A"
    accuracy_details = "Column 'attendance_date' not found"

# ✅ 6. Validity (attendance_status values)
if 'attendance_data' in df.columns:
    valid_statuses = ['P', 'X', 'E', 'L']
    invalid_statuses_count = (~df['attendance_data'].isin(valid_statuses)).sum()
    validity_result = "Fail ❌" if invalid_statuses_count > 0 else "Pass ✅"
    validity_details = f"{invalid_statuses_count} invalid values in 'attendance_data'"
else:
    validity_result = "N/A"
    validity_details = "Column 'attendance_status' not found"

# 📊 إنشاء تقرير جودة البيانات
attendance_quality_report = pd.DataFrame({
    "Dimension": [
        "Completeness",
        "Uniqueness",
        "Consistency",
        "Timeliness",
        "Validity"
    ],
    "Result": [
        completeness_result,
        uniqueness_result,
        consistency_result,
        timeliness_result,
        validity_result
    ],
    "Details": [
        completeness_details,
        uniqueness_details,
        consistency_details,
        timeliness_details,
        validity_details
    ]
})

# 📋 طباعة التقرير
print(f"\nTotal rows analyzed: {len(df)}")
print("\n📊 Data Quality Report:")
print(attendance_quality_report)

# 📈 توزيع حالات الحضور إن وجد
if 'attendance_status' in df.columns:
    print("\n📌 Attendance Status Distribution (%):")
    print(df['attendance_status'].value_counts(normalize=True) * 100)

attendance_quality_report

attendance_quality_report.to_csv('attendance_quality_report.csv', index=False)

# Completeness
missing_summary = users_df.isnull().sum()
print("Missing values per column:\n", missing_summary)

# Uniqueness
duplicates = users_df.duplicated().sum()
print(f"Number of duplicate rows: {duplicates}")

# Duplicate IDs (if there's an 'id' column)
if 'id' in users_df.columns:
    duplicate_ids = users_df['id'].duplicated().sum()
    print(f"Number of duplicate IDs: {duplicate_ids}")

# Validity: Check if fields match expected formats.
import re

pattern = r'^[\w\.-]+@[\w\.-]+\.\w+$'
valid_emails = users_df['email'].str.match(pattern)
print(f"Invalid emails: {len(users_df[~valid_emails])}")

# Validity: Check if fields match expected formats.
student_pattern = r'^Stud\d{4}$'
valid_ids = users_df['student_id'].str.match(student_pattern)
print(f"Invalid student IDs: {len(users_df[~valid_ids])}")

print("Unique client IDs:", users_df['client_id'].unique())

# Consistency: Check if fields like role have consistent formatting:
print("Unique roles:", users_df['role'].unique())

data_quality_report = pd.DataFrame({
    "Dimension": [
        "Completeness",
        "Uniqueness",
        "Validity",
        "Accuracy",
        "Consistency"
    ],
    "Result": [
        "Pass ✅",
        "Fail ❌",  # because of 1876 duplicate IDs
        "Pass ✅",
        "Issue ⚠️",
        "Fail ❌"   # because of inconsistent role values
    ],
    "Details": [
        "No nulls detected",
        "1876 duplicate IDs found",
        "Emails and student_ids match expected formats",
        "Client and name accuracy needs verification",
        "Roles contain inconsistent and repeated values"
    ]
})

data_quality_report

data_quality_report.to_csv('users_data_quality_report2.csv', index=False)

"""# cohorts"""

query = f"SELECT * FROM cohorts"
cohorts_df=pd.read_sql(query, engine)
cohorts_df.head()

# Completeness
missing_summary = cohorts_df.isnull().sum()
print("Missing values per column:\n", missing_summary)

# Uniqueness
duplicates = cohorts_df.duplicated().sum()
print(f"Number of duplicate rows: {duplicates}")

# Duplicate IDs
duplicate_ids = cohorts_df['id'].duplicated().sum()
print(f"Number of duplicate IDs: {duplicate_ids}")

# Validity checks
# Check if days column contains valid format (empty dict or dict-like)
try:
    days_valid = cohorts_df['days'].apply(lambda x: x == '{}' or isinstance(x, dict) or pd.isna(x)).all()
    print(f"Invalid days format: {len(cohorts_df[~cohorts_df['days'].apply(lambda x: x == '{}' or isinstance(x, dict) or pd.isna(x))])}")
except Exception as e:
    print(f"Days validation error: {str(e)}")
    days_valid = False

# Check if times column is non-empty string
times_valid = cohorts_df['times'].apply(lambda x: isinstance(x, str) and len(x) > 0).all()
print(f"Invalid times values: {len(cohorts_df[~cohorts_df['times'].apply(lambda x: isinstance(x, str) and len(x) > 0)])}")

# Check client_id format
client_id_valid = cohorts_df['client_id'].apply(lambda x: isinstance(x, str) and x.startswith('client_')).all()
print(f"Invalid client IDs: {len(cohorts_df[~cohorts_df['client_id'].apply(lambda x: isinstance(x, str) and x.startswith('client_'))])}")

# Check created_at is valid datetime
try:
    pd.to_datetime(cohorts_df['created_at'])
    datetime_valid = True
except Exception as e:
    datetime_valid = False
    print(f"Invalid datetime values in created_at: {str(e)}")

# Create data quality report
cohorts_quality_report = pd.DataFrame({
    "Dimension": [
        "Completeness",
        "Uniqueness",
        "Validity",
        "Accuracy",
        "Consistency"
    ],
    "Result": [
        "Warning ⚠️" if missing_summary[['end_date', 'start_date']].sum() > 0 else "Pass ✅",
        "Fail ❌" if duplicate_ids > 0 else "Pass ✅",
        "Warning ⚠️" if not all([days_valid, times_valid, client_id_valid, datetime_valid]) else "Pass ✅",
        "Needs Verification 🔍",
        "Warning ⚠️" if cohorts_df['client_id'].nunique() > 1 else "Pass ✅"
    ],
    "Details": [
        f"Missing values in end_date ({missing_summary['end_date']}) and start_date ({missing_summary['start_date']})",
        f"{duplicate_ids} duplicate IDs found (critical issue)" if duplicate_ids > 0 else "No duplicate IDs found",
        f"Validity issues: Days format ({not days_valid}), Times ({not times_valid}), Client IDs ({not client_id_valid}), Dates ({not datetime_valid})",
        "Manual verification needed for cohort names and program mappings",
        f"{cohorts_df['client_id'].nunique()} different client IDs found" if cohorts_df['client_id'].nunique() > 1 else "Consistent client IDs"
    ]
})

cohorts_quality_report

cohorts_quality_report.to_csv('cohorts_quality_report.csv', index=False)

"""Breakdown of the Validity Status:
Days format (True)

✅ Valid: The days column passed its validation check (all values are either empty dicts {}, proper dictionaries, or null)

This means the format/structure of data in this column is correct

Times (False)

❌ Invalid: The times column failed its validation check

This means some values either:

Aren't strings

Are empty strings

Don't match expected time format

Client IDs (False)

❌ Invalid: The client_id column failed its validation check

Some values don't start with 'client_' as expected

May contain:

Null values

Different prefix

Malformed entries

Dates (False)

❌ Invalid: The date-related columns failed validation

Likely issues with:

created_at contains non-datetime values

end_date/start_date have invalid formats

Unexpected null values where not allowed

# cohort enrollments
"""

query = f"SELECT * FROM cohort_enrollments"
enrollments_df = pd.read_sql(query, engine)
enrollments_df.head()

"""# assiemnets"""

query = f"select * from assiements"
assignments_df = pd.read_sql(query, engine)
assignments_df.head()

# Data Quality Checks for assignments
# =================================

# 1. Completeness
missing_summary = assignments_df.isnull().sum()

# 2. Uniqueness
duplicate_rows = assignments_df.duplicated().sum()
duplicate_ids = assignments_df['Student_ID'].duplicated().sum()

# 3. Validity Checks
# Check Student_ID format
student_id_valid = assignments_df['Student_ID'].str.match(r'^Stud\d{4}$').all()

# Check week scores format (percentage strings)
week_cols = [f'week{i}' for i in range(1,8)]
percent_valid = assignments_df[week_cols].apply(lambda x: x.str.endswith('%')).all().all()

# Check final_score is numeric between 0-100
final_score_valid = ((assignments_df['final_score'] >= 0) & (assignments_df['final_score'] <= 100)).all()

# Check name column consistency
name_valid = assignments_df['name'].apply(lambda x: isinstance(x, str) and len(x) > 0).all()

# 4. Consistency
# Check if final_score matches weekly percentages
def calculate_expected_score(row):
    week_scores = [float(row[col].strip('%')) for col in week_cols]
    return sum(week_scores) / len(week_scores)

assignments_df['calculated_score'] = assignments_df.apply(calculate_expected_score, axis=1)
score_consistency = (abs(assignments_df['final_score'] - assignments_df['calculated_score']) < 1).all()

# 5. Anomaly Detection
# Check for suspicious patterns (all 100% scores)
all_perfect = (assignments_df[week_cols] == '100%').all(axis=1).sum()
perfect_final = (assignments_df['final_score'] == 100).sum()

# Data Quality Report
# ===================
assignments_quality_report = pd.DataFrame({
    "Dimension": [
        "Completeness",
        "Uniqueness",
        "Validity",
        "Consistency"
    ],
    "Result": [
        "Pass ✅" if missing_summary.sum() == 0 else "Fail ❌",
        "Pass ✅" if duplicate_rows == 0 and duplicate_ids == 0 else "Fail ❌",
        "Pass ✅" if all([student_id_valid, percent_valid, final_score_valid, name_valid]) else "Fail ❌",
        "Warning ⚠️" if not score_consistency else "Pass ✅"
    ],
    "Details": [
        "No missing values detected",
        f"{duplicate_rows} duplicate rows, {duplicate_ids} duplicate Student_IDs",
        f"Student IDs: {student_id_valid}, Week scores: {percent_valid}, Final scores: {final_score_valid}, Names: {name_valid}",
        f"{len(assignments_df[~score_consistency])} records with final_score ≠ weekly average" if not score_consistency else "Scores consistent"
    ]
})

assignments_quality_report

"""# Cohort Assignment"""

query = f"select * from Cohort_Assignment"
Cohort_Assignment_df = pd.read_sql(query, engine)
Cohort_Assignment_df.head()

query = f"select * from cohort_courses"
cohort_courses_df = pd.read_sql(query, engine)
cohort_courses_df.head()

# Data Quality Checks for Cohort Assignment
# =========================================

# 1. Completeness
missing_summary = Cohort_Assignment_df.isnull().sum()

# 2. Uniqueness
duplicate_rows = Cohort_Assignment_df.duplicated().sum()
duplicate_ids = Cohort_Assignment_df['studentID'].duplicated().sum()

# 3. Validity Checks
# Check studentID format (e.g., Stud0427)
student_id_valid = Cohort_Assignment_df['studentID'].str.match(r'^Stud\d{4}$').all()

# Check date format
date_columns = ['start_date', 'end_date']
date_valid = True
for col in date_columns:
    try:
        pd.to_datetime(Cohort_Assignment_df[col], format="%d-%b-%Y")
    except:
        date_valid = False

# Check name non-empty strings
name_valid = Cohort_Assignment_df['name'].apply(lambda x: isinstance(x, str) and len(x.strip()) > 0).all()

# Check level is in expected set (e.g., L1, L2, L3, etc.)
level_valid = Cohort_Assignment_df['level'].str.match(r'^L\d$').all()

# 4. Consistency
# Check that cohort_schedule string contains the start and end dates
def cohort_schedule_check(row):
    return row['start_date'] in row['cohort_schedule'] and row['end_date'] in row['cohort_schedule']

cohort_schedule_consistency = Cohort_Assignment_df.apply(cohort_schedule_check, axis=1).all()

# 5. Anomaly Detection
# Check if same student is marked Withdraw across all rows
withdrawn_students = Cohort_Assignment_df.groupby('studentID')['cohort_status'].apply(lambda x: (x == 'Withdraw').all())
all_withdrawn = withdrawn_students.sum()

# Data Quality Report
# ===================
cohort_quality_report = pd.DataFrame({
    "Dimension": [
        "Completeness",
        "Uniqueness",
        "Validity",
        "Consistency"
    ],
    "Result": [
        "Pass ✅" if missing_summary.sum() == 0 else "Fail ❌",
        "Pass ✅" if duplicate_rows == 0 and duplicate_ids == 0 else "Fail ❌",
        "Pass ✅" if all([student_id_valid, date_valid, name_valid, level_valid]) else "Fail ❌",
        "Pass ✅" if cohort_schedule_consistency else "Warning ⚠️"
    ],
    "Details": [
        f"{missing_summary.sum()} missing values across {missing_summary[missing_summary > 0].count()} columns",
        f"{duplicate_rows} duplicate rows, {duplicate_ids} duplicate studentIDs",
        f"Student IDs: {student_id_valid}, Dates: {date_valid}, Names: {name_valid}, Levels: {level_valid}",
        "All cohort_schedule strings contain start and end dates" if cohort_schedule_consistency else "Some cohort_schedule values do not match date columns"
    ]
})

cohort_quality_report

# Data Quality Checks for cohort_courses
# ===================================

# 1. Completeness
missing_summary = cohort_courses_df.isnull().sum()

# 2. Uniqueness
duplicate_rows = cohort_courses_df.duplicated().sum()
duplicate_ids = cohort_courses_df['id'].duplicated().sum()

# 3. Validity Checks
# Check ID columns are positive integers
id_valid = (cohort_courses_df[['id', 'exam_id', 'cohort_id']] > 0).all().all()

# Check client_id format
client_id_valid = cohort_courses_df['client_id'].str.startswith('client_').all()

# Check published is binary (0/1)
published_valid = cohort_courses_df['published'].isin([0, 1]).all()

# Check datetime formats
try:
    pd.to_datetime(cohort_courses_df['created_at'])
    datetime_valid = True
except:
    datetime_valid = False

# Improved weight column JSON structure validation
def is_valid_weight(weight):
    try:
        if pd.isna(weight):
            return False
        if isinstance(weight, str):
            import json
            weight = json.loads(weight.replace("'", '"'))  # Safer JSON parsing
        required_keys = ['quizzes', 'projects', 'assignments', 'attendances', 'soft_skills']
        if not all(k in weight for k in required_keys):
            return False
        if not isinstance(weight['attendances'], dict):
            return False
        attendance_keys = ['late', 'absence', 'excused', 'present']
        if not all(k in weight['attendances'] for k in attendance_keys):
            # Check for alternative structure with 'total' and 'participation'
            if 'total' not in weight['attendances'] or 'participation' not in weight['attendances']:
                return False
            if not all(k in weight['attendances']['participation'] for k in attendance_keys):
                return False
        return True
    except:
        return False

weight_valid = cohort_courses_df['weight'].apply(is_valid_weight).all()

# 4. Consistency
current_time = pd.Timestamp.now()
date_consistency = (pd.to_datetime(cohort_courses_df['created_at']) <= current_time).all()

# 5. Referential Integrity - Fixed query
# Get reference tables
cohorts_df = pd.read_sql("SELECT id FROM cohorts", engine)
exams_df = pd.read_sql("SELECT DISTINCT exam_id FROM cohort_courses WHERE exam_id IS NOT NULL", engine)

# Check cohort_ids exist in cohorts table
invalid_cohorts = cohort_courses_df[~cohort_courses_df['cohort_id'].isin(cohorts_df['id'])]
cohort_ref_valid = len(invalid_cohorts) == 0

# Check exam_ids exist in exams table
invalid_exams = cohort_courses_df[(cohort_courses_df['exam_id'].notna()) &
                                (~cohort_courses_df['exam_id'].isin(exams_df['exam_id']))]
exam_ref_valid = len(invalid_exams) == 0

# Data Quality Report
# ===================
cohort_courses_quality_report = pd.DataFrame({
    "Dimension": [
        "Completeness",
        "Uniqueness",
        "Validity",
        "Consistency",
        "Referential Integrity"
    ],
    "Result": [
        "Warning ⚠️" if missing_summary[['description', 'resource_id']].sum() > 0 else "Pass ✅",
        "Fail ❌" if duplicate_ids > 0 else "Pass ✅",
        "Fail ❌" if not weight_valid else "Pass ✅" if all([id_valid, client_id_valid, published_valid, datetime_valid]) else "Fail ❌",
        "Pass ✅",
        "Fail ❌" if not exam_ref_valid else "Pass ✅"
    ],
    "Details": [
        f"Nullable fields: description ({missing_summary['description']} nulls), resource_id ({missing_summary['resource_id']} nulls)",
        f"Duplicate IDs found: {duplicate_ids} (critical issue)",
        f"Weight JSON validation {'failed' if not weight_valid else 'passed'}. Other checks: IDs ({id_valid}), Client IDs ({client_id_valid}), Published ({published_valid}), Dates ({datetime_valid})",
        "All dates are chronologically valid",
        f"Referential integrity: Cohorts ({'valid' if cohort_ref_valid else f'{len(invalid_cohorts)} invalid'}), Exams ({'valid' if exam_ref_valid else f'{len(invalid_exams)} invalid'})"
    ]
})

cohort_courses_quality_report

cohort_courses_quality_report.to_csv('cohort_courses_quality_report.csv', index=False)

"""# cohort_course_enrollments"""

query = f"SELECT * from cohort_course_enrollments"
cohort_course_enrollments_df = pd.read_sql(query, engine)
cohort_course_enrollments_df.head()

# Data Quality Checks for cohort_course_enrollments (excluding metadata)
# =====================================================================

import pandas as pd
from datetime import datetime

# Remove Airbyte metadata columns
cols_to_analyze = ['id', 'status', 'exam_id', 'user_id', 'client_id', 'created_at', 'cohort_course_id']
enrollments_df = cohort_course_enrollments_df[cols_to_analyze]

# 1. Completeness
missing_summary = enrollments_df.isnull().sum()

# 2. Uniqueness
duplicate_rows = enrollments_df.duplicated().sum()
duplicate_ids = enrollments_df['id'].duplicated().sum()

# 3. Validity Checks
# Check ID formats (positive integers)
id_valid = (enrollments_df['id'] > 0).all()
user_id_valid = (enrollments_df['user_id'] > 0).all()
cohort_course_id_valid = (enrollments_df['cohort_course_id'] > 0).all()

# Check status values (expected: enrolled, completed, etc.)
status_values = enrollments_df['status'].unique()
status_valid = set(status_values).issubset({'enrolled', 'completed', 'dropped'})  # Add expected values

# Check timestamp format
created_at_valid = pd.to_datetime(enrollments_df['created_at'], errors='coerce').notna().all()

# Check client_id format (starts with 'client_' and has valid suffix)
client_id_valid = enrollments_df['client_id'].str.match(r'^client_[a-zA-Z0-9]+$').all()

# 4. Consistency
# Check if created_at dates are reasonable (not in future)
current_date = pd.to_datetime(datetime.now())
time_consistency = (pd.to_datetime(enrollments_df['created_at']) <= current_date).all()

# Check if all enrolled records have null exam_id (if expected)
exam_id_consistency = True
if 'enrolled' in status_values:
    enrolled_with_exam = ((enrollments_df['status'] == 'enrolled') &
                         (enrollments_df['exam_id'].notnull())).sum()
    exam_id_consistency = enrolled_with_exam == 0

# 5. Anomaly Detection
# Check for duplicate user_id + cohort_course_id combinations
user_cohort_duplicates = enrollments_df.duplicated(subset=['user_id', 'cohort_course_id'], keep=False).sum()

# Check for users enrolled in same course multiple times
multiple_enrollments = enrollments_df.groupby(['user_id', 'cohort_course_id'])['id'].count()
multiple_enrollments = multiple_enrollments[multiple_enrollments > 1].count()

# Data Quality Report
# ===================
enrollments_quality_report = pd.DataFrame({
    "Dimension": [
        "Completeness",
        "Uniqueness",
        "Validity",
        "Consistency",
        "Anomalies"
    ],
    "Result": [
        "Warning ⚠️" if missing_summary['exam_id'] > 0 else "Pass ✅",
        "Pass ✅" if duplicate_rows == 0 and duplicate_ids == 0 else "Fail ❌",
        "Pass ✅" if all([id_valid, user_id_valid, cohort_course_id_valid,
                         status_valid, created_at_valid, client_id_valid]) else "Fail ❌",
        "Pass ✅" if time_consistency and exam_id_consistency else "Warning ⚠️",
        "Warning ⚠️" if user_cohort_duplicates > 0 else "Pass ✅"
    ],
    "Details": [
        f"Missing values: exam_id ({missing_summary['exam_id']}), others complete",
        f"{duplicate_rows} duplicate rows, {duplicate_ids} duplicate IDs",
        f"IDs valid: {id_valid}, Statuses: {status_values}, Timestamps valid: {created_at_valid}",
        f"Time consistency: {time_consistency}, Exam ID rules: {exam_id_consistency}",
        f"{user_cohort_duplicates} user+cohort duplicates found"
    ]
})

enrollments_quality_report

"""# Quizzes"""

query = f"SELECT * from Quizzes"
Quizzes_df = pd.read_sql(query, engine)
Quizzes_df.head(50)

# Data Quality Checks for Quizzes
# ==============================

# 1. Completeness
missing_summary = Quizzes_df.isnull().sum()

# 2. Uniqueness
duplicate_rows = Quizzes_df.duplicated().sum()
duplicate_ids = Quizzes_df['Student_ID'].duplicated().sum()

# 3. Validity Checks
# Check Student_ID format (e.g., Stud0427)
student_id_valid = Quizzes_df['Student_ID'].str.match(r'^Stud\d{4}$').all()

# Check quiz columns are non-null (assuming all quizzes should have data)
quiz_columns = ['Quiz1', 'Quiz2', 'Quiz3', 'Quiz4', 'Quiz5', 'Quiz6', 'Quiz7', 'Quiz8']
quiz_valid = Quizzes_df[quiz_columns].notnull().all().all()

# Check name non-empty strings
name_valid = Quizzes_df['name'].apply(lambda x: isinstance(x, str) and len(x.strip()) > 0).all()

# 4. Consistency
# Check if all quizzes have consistent values (if quizzes should not have zero values or negative)
quiz_value_consistency = (Quizzes_df[quiz_columns] >= 0).all().all()

# 5. Anomaly Detection
# Check for any duplicate student IDs
duplicate_student_ids = Quizzes_df['Student_ID'].duplicated().sum()

# Data Quality Report
# ===================
quizzes_quality_report = pd.DataFrame({
    "Dimension": [
        "Completeness",
        "Uniqueness",
        "Validity",
        "Consistency",
        "Anomalies"
    ],
    "Result": [
        "Pass ✅" if missing_summary.sum() == 0 else "Fail ❌",
        "Pass ✅" if duplicate_rows == 0 and duplicate_ids == 0 else "Fail ❌",
        "Pass ✅" if all([student_id_valid, quiz_valid, name_valid]) else "Fail ❌",
        "Pass ✅" if quiz_value_consistency else "Fail ❌",
        "Pass ✅" if duplicate_student_ids == 0 else "Warning ⚠️"
    ],
    "Details": [
        f"{missing_summary.sum()} missing values across {missing_summary[missing_summary > 0].count()} columns",
        f"{duplicate_rows} duplicate rows, {duplicate_ids} duplicate student IDs",
        f"Student IDs: {student_id_valid}, Quizzes valid: {quiz_valid}, Names valid: {name_valid}",
        "All quiz values are non-negative" if quiz_value_consistency else "Some quiz values are negative or zero",
        f"{duplicate_student_ids} duplicate student IDs found"
    ]
})

quizzes_quality_report