# -*- coding: utf-8 -*-
"""Stage2-DataCleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mG35vvkg2gmiSV23oErcB6Wh0oQgz1wG

# Install libraries
"""

!pip install SQLAlchemy
!pip install PyMySQL

import pandas as pd

"""#  ☑️ Workflow: Clean AWS RDS Table


*   Step 1: Connect to AWS RDS from Colab (Make Connection)
*   Step 2: Clean it up using Query
*   Step 3: Replace the cleaned file to the old one

\# Step 1: Connect to AWS RDS from Colab (Make Connection)
"""

from sqlalchemy import create_engine

ENDPOINT = "demo-rds-mysql-db.csb002k2ask1.us-east-1.rds.amazonaws.com"
PORT = "3306"
USERNAME = "admin"
PASSWORD = "Shmuokh001*"
DATABASENAME = "demo_db"

engine = create_engine(f"mysql+pymysql://{USERNAME}:{PASSWORD}@{ENDPOINT}:{PORT}/{DATABASENAME}")

"""# Test Connection"""

from sqlalchemy import text

with engine.connect() as connection:
  result = connection.execute(text("SHOW TABLES"))
  tables = result.fetchall()
  print(tables)

"""# 1. Assiements Table 🟩"""

# Run query using pandas
import pandas as pd
query = "SELECT * FROM assiements;"  # Adjust table name if needed
df1 = pd.read_sql(query, engine)

# Preview the data
df1.head()

"""The Result of Assiements cleaning

The Assiements table is very clean and straightforward

# 3. Attendance Table  🟩
"""

# Run query using pandas
import pandas as pd
query = "SELECT * FROM attendance;"  # Adjust table name if needed
df3 = pd.read_sql(query, engine)

# Preview the data
df3.head()

#Quick EDA

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Basic info
print("Shape:", df3.shape)
print("\nData types:\n", df3.dtypes)
#print("\nFirst 5 rows:\n", df.head())

# 2. Missing Values & Duplicates
print("\nMissing values per column:\n", df3.isnull().sum())
print("\nTotal duplicate rows:", df3.duplicated().sum())

# 3. Descriptive statistics
#print("\nDescriptive statistics (numerical):\n", df3.describe())
#print("\nDescriptive statistics (categorical):\n", df3.describe(include=['O']))

# 4. Value counts for categorical features
cat_cols = df3.select_dtypes(include='object').columns
for col in cat_cols:
    print(f"\nValue counts for {col}:\n", df3[col].value_counts())

# 5. Correlation analysis (numerical)
corr = df3.corr(numeric_only=True)
print("\nCorrelation matrix:\n", corr)

# Remove duplicates
df3_cleaned = df3.drop_duplicates()

print("Number of rows:", len(df3_cleaned))

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


# 1. Normalize (make lowercase)
df3['attendance_data'] = df3['attendance_data'].str.lower()

# 2. Map codes to descriptive values
code_map = {
    'p': 'Present',
    'P': 'Present',
    'x': 'Absent',
    'X': 'Absent',
    'e': 'Excused',
    'l': 'Leave'
}
df3_cleaned = df3['attendance_status'] = df3['attendance_data'].map(code_map)

# 3. Show the value counts
print(df3['attendance_status'].value_counts())

# 4. Visualize the distribution
plt.figure(figsize=(8,5))
sns.countplot(data=df3, x='attendance_status', order=df3['attendance_status'].value_counts().index, palette="Set2")
plt.title('Attendance Status Distribution')
plt.xlabel('Attendance Status')
plt.ylabel('Count')
plt.show()

# Replace table with cleaned version
df3.to_sql('attendance', engine, if_exists='replace', index=False)

# Run query using pandas
#import pandas as pd
query = "SELECT * FROM attendance;"  # Adjust table name if needed
df3 = pd.read_sql(query, engine)

# Preview the data
df3.head()

"""As result of cleaning:

- Delete 5 duplicates rows
- Create new column called 'attendance_status'  by mapping [attendance_data] to be Present, Absent, Excused, and Leave.

# 4. Chapters Table  🟩
"""

# Run query using pandas
import pandas as pd
query = "SELECT * FROM chapters;"  # Adjust table name if needed
df4 = pd.read_sql(query, engine)

# Preview the data
df4.head()

# Drop metadata columns
#df4.drop(columns=['resource_id','_airbyte_raw_id', '_airbyte_extracted_at', '_airbyte_meta'], inplace=True)

# Preview the cleaned data
#print("Cleaned chapters data:")
#print(df4.head())

df4.head()

# Optional: Save to a new table or CSV
# df_chapters.to_sql('chapters_cleaned', engine, index=False, if_exists='replace')
# OR
# df_chapters.to_csv('chapters_cleaned.csv', index=False)

# Mapping [exam_id] using "cohort courses"  table

# Step 1: Create a mapping from cohort_course_id to exam_id
course_id_to_exam = cohort_courses_df.set_index('id')['exam_id'].to_dict()

# Step 2: Fill missing exam_id in chapters
df4['exam_id'] = df4['exam_id'].fillna(
    df4['cohort_course_id'].map(course_id_to_exam)
)

# Change data type
df4 = df4.infer_objects(copy=False)

# Drop unused column
df4.drop(columns=['published','resource_id','_airbyte_raw_id', '_airbyte_extracted_at', '_airbyte_meta'], inplace=True)

# Fill null values in description column
df4['description'] = df4['description'].replace('', pd.NA).fillna("No description provided.")

# Replace the new table after cleaning to the old one in RDS
df4.to_sql('chapters', engine, index=False, if_exists='replace')

"""# Cohort Courses Table 🟩"""

# Run query using pandas
import pandas as pd
query = "SELECT * FROM cohort_courses;"  # Adjust table name if needed
cohort_courses_df = pd.read_sql(query, engine)

# Preview the data
cohort_courses_df.head()

cohort_courses_df.columns

# 1. Drop unnecessary columns
cols_to_drop = ['_airbyte_raw_id', '_airbyte_extracted_at', '_airbyte_meta', 'resource_id']
cohort_courses_df.drop(columns=cols_to_drop, inplace=True, errors='ignore')

# 2. Clean course names (remove leading special chars)
cohort_courses_df['name'] = cohort_courses_df['name'].str.replace(r'^[-&]\s*', '', regex=True).str.strip()

# 3. clean created_at colmn
cohort_courses_df['created_at'] = pd.to_datetime(cohort_courses_df['created_at']).dt.date

import pandas as pd
import ast

def extract_weights(weight_data):
    """Extract weights from JSON/dict while handling all edge cases"""
    try:
        if pd.isna(weight_data):
            return pd.Series({k: 0 for k in weight_columns})

        if isinstance(weight_data, str):
            weights = ast.literal_eval(weight_data)
        else:
            weights = weight_data

        # Main weights
        result = {
            'quiz_weight': weights.get('quizzes', 0),
            'project_weight': weights.get('projects', 0),
            'assignment_weight': weights.get('assignments', 0),
            'soft_skills_weight': weights.get('soft_skills', 0)
        }

        # Handle both nested and flat attendance structures
        attendances = weights.get('attendances', {})
        if isinstance(attendances, dict):
            result['attendance_total_weight'] = attendances.get('total', 0)
            participation = attendances.get('participation', attendances)
            result.update({
                'attendance_late_weight': participation.get('late', 0),
                'attendance_absence_weight': participation.get('absence', 0),
                'attendance_excused_weight': participation.get('excused', 0),
                'attendance_present_weight': participation.get('present', 0)
            })

        return pd.Series(result)

    except:
        return pd.Series({k: 0 for k in weight_columns})

# Define all weight columns we'll create
weight_columns = [
    'quiz_weight', 'project_weight', 'assignment_weight',
    'soft_skills_weight', 'attendance_total_weight',
    'attendance_late_weight', 'attendance_absence_weight',
    'attendance_excused_weight', 'attendance_present_weight'
]

# Extract weights directly into new columns
cohort_courses_df[weight_columns] = cohort_courses_df['weight'].apply(extract_weights)

# Calculate total weight for validation
cohort_courses_df['total_weight'] = (
    cohort_courses_df['quiz_weight'] +
    cohort_courses_df['project_weight'] +
    cohort_courses_df['assignment_weight'] +
    cohort_courses_df['soft_skills_weight'] +
    cohort_courses_df['attendance_total_weight']
)

# Group topics by cohort_course_id and check if any topic is published
published_status = topics_df.groupby('cohort_course_id')['published'].any().reset_index()

# Merge the published status into cohort_courses
cohort_courses_df = cohort_courses_df.merge(
    published_status,
    left_on='id',
    right_on='cohort_course_id',
    how='left',
    suffixes=('', '_from_topics')
)

# Update the published column
cohort_courses_df['published'] = cohort_courses_df['published_from_topics'].fillna(False)

# Drop the extra column
cohort_courses_df.drop(columns=['published_from_topics', 'cohort_course_id'], inplace=True)
cohort_courses_df['published'] = cohort_courses_df['published'].astype(int)

cohort_courses_df.info()

# delete weight	column
# cohort_courses_df.drop(columns=['weight'], inplace=True)
cohort_courses_df.drop(columns=['total_weight'], inplace=True)

cohort_courses_df.head()

table_name2 = 'cohort_courses'
# Save to MySQL RDS
cohort_courses_df.to_sql(
    name=table_name2,          # Table name
    con=engine,               # SQLAlchemy engine
    if_exists='replace',      # Options: 'fail', 'replace', 'append'
    index=False,              # Don't write DataFrame index as a column
    chunksize=1000            # Optional: write in batches for large DataFrames
)

print(f"Transferred {len(cohort_courses_df)} rows to {table_name2} in MySQL RDS after cleaning")

# Cleaning for Description column
cohort_courses_df['description'] = cohort_courses_df['description'].replace('', pd.NA).fillna("No description provided.")

# Replace the new table after cleaning to the old one in RDS
cohort_courses_df.to_sql('cohort_courses', engine, index=False, if_exists='replace')

# Display it
cohort_courses_df.head()

"""# Topics Table 🟩"""

# Run query using pandas
import pandas as pd
query = "SELECT * FROM topics;"  # Adjust table name if needed
topics_df = pd.read_sql(query, engine)

# Preview the data
topics_df.head()

# Drop metadata columns
topics_df.drop(columns=['_airbyte_oraw_id', '_airbyte_extracted_at', '_airbyte_meta', 'resource_id'], inplace=True)

# نبدأ بعمل نسخة فقط للأعمدة المهمة من cohort_courses
cohort_courses_subset = cohort_courses_df[['id', 'exam_id', 'client_id']].copy()
cohort_courses_subset.rename(columns={'id': 'cohort_course_id'}, inplace=True)

# نحاول نربط المواضيع (topics) بالدورات (cohort_courses) حسب exam_id و client_id
topics_filled = topics_df.merge(
    cohort_courses_subset,
    on='client_id',
    how='left',
    suffixes=('', '_from_courses')
)

# نملأ cohort_course_id فقط إذا كان NaN
topics_filled['cohort_course_id'] = topics_filled['cohort_course_id'].fillna(
    topics_filled['cohort_course_id_from_courses']
)

# نملأ exam_id فقط إذا كان NaN
topics_filled['exam_id'] = topics_filled['exam_id'].fillna(
    topics_filled['exam_id_from_courses']
)

# نحذف الأعمدة المكررة
topics_filled.drop(columns=['cohort_course_id_from_courses', 'exam_id_from_courses'], inplace=True)

# هذا هو الجدول النهائي
topics_df = topics_filled

topics_df['created_at'] = pd.to_datetime(topics_df['created_at']).dt.date

topics_df.head()

# Replace table with cleaned version
topics_df.to_sql('topics', engine, if_exists='replace', index=False)

"""# 5. Choices Table  🟩


"""

# Run query using pandas
import pandas as pd
query = "SELECT * FROM choices;"  # Adjust table name if needed
choices_df = pd.read_sql(query, engine)

# Preview the data
choices_df.head()

# Drop unused column
choices_df.drop(columns=['grade','notes','comment','_airbyte_raw_id','_airbyte_extracted_at', '_airbyte_meta'], inplace=True)

# Preview the data
choices_df.head()

missing_choices = choices_df[choices_df['choice'].isna()]
print(missing_choices.sample(5))  # Inspect a few randomly

print(choices_df['choice'].isna().sum())
print(choices_df['choice'].dtype)

choices_df['choice'] = choices_df['choice'].replace('', pd.NA)
choices_df['choice'] = choices_df['choice'].apply(lambda x: x.strip() if isinstance(x, str) else x)

# Replace the new table after cleaning to the old one in RDS
choices_df.to_sql('choices', engine, index=False, if_exists='replace')

"""# 5. user_exams Table 🟩


"""

# Run query using pandas
import pandas as pd
query = "SELECT * FROM user_exams;"  # Adjust table name if needed
user_exams_df = pd.read_sql(query, engine)

# Preview the data
user_exams_df.head()

# 1. Drop unnecessary columns
cols_to_drop = ['_airbyte_raw_id', '_airbyte_extracted_at', '_airbyte_meta']
user_exams_df.drop(columns=cols_to_drop, inplace=True, errors='ignore')

user_exams_df['created_at'] = pd.to_datetime(user_exams_df['created_at']).dt.date

# دمج الجداول بناءً على العمود المشترك
merged_df = user_exams_df.merge(
    cohort_courses_df[['id', 'exam_id']],
    left_on='cohort_course_id',
    right_on='id',
    how='left',
    suffixes=('', '_from_courses')
)

# تحديث عمود exam_id في user_exams_df بالقيم من جدول cohort_courses
user_exams_df['exam_id'] = merged_df['exam_id_from_courses']

user_exams_df['progress_percent'] = (
    user_exams_df['stars_count'] / user_exams_df['stars_total_count']
) * 100

user_exams_df['progress_percent'] = user_exams_df['progress_percent'].round(1)

user_exams_df.head()

user_exams_df.isna().sum()

# Replace the new table after cleaning to the old one in RDS
user_exams_df.to_sql('user_exams', engine, index=False, if_exists='replace')

"""# 6. Cohorts Table  🟩"""

# Run query using pandas
import pandas as pd
query = "SELECT * FROM cohorts;"  # Adjust table name if needed
df6 = pd.read_sql(query, engine)

# Preview the data
df6.head()

# Run query using pandas
import pandas as pd
query = "SELECT * FROM cohorts;"  # Adjust table name if needed
df6 = pd.read_sql(query, engine)

# Preview the data
df6.head()

df6.shape

# Drop unused column
df6.drop(columns=['days','times','end_date','start_date','resource_id','_airbyte_raw_id','_airbyte_extracted_at', '_airbyte_meta'], inplace=True)

# Preview the data
df6.head()

# Replace the new table after cleaning to the old one in RDS
df6.to_sql('cohorts', engine, index=False, if_exists='replace')

"""# Attempt Table  🟩

"""

# Run query using pandas
import pandas as pd
query = "SELECT * FROM attempts;"  # Adjust table name if needed
attempts_df = pd.read_sql(query, engine)

# Preview the data
attempts_df.head()

# أنشئ قاموس يربط cohort_course_id بـ exam_id و cohort_id من جدول cohort_courses
course_id_to_exam = cohort_courses_df.set_index('id')['exam_id'].to_dict()
course_id_to_cohort = cohort_courses_df.set_index('id')['cohort_id'].to_dict()

# عبّئ القيم المفقودة في exam_id و cohort_id باستخدام القواميس
attempts_df['exam_id'] = attempts_df['exam_id'].fillna(attempts_df['cohort_course_id'].map(course_id_to_exam))
attempts_df['cohort_id'] = attempts_df['cohort_id'].fillna(attempts_df['cohort_course_id'].map(course_id_to_cohort))

attempts_df['created_at'] = pd.to_datetime(attempts_df['created_at']).dt.date
attempts_df['submitted_at'] = pd.to_datetime(attempts_df['submitted_at']).dt.date

attempts_df.drop(columns=['resource_id'], inplace=True)
attempts_df.drop(columns=['duration'], inplace=True)
# Drop metadata columns
attempts_df.drop(columns=['_airbyte_raw_id', '_airbyte_extracted_at', '_airbyte_meta'], inplace=True)

import yaml

def clean_to_csv(yaml_str):
    if pd.isna(yaml_str) or yaml_str.strip() in ['', 'NULL', 'None']:
        return None
    try:
        cleaned = yaml.safe_load(yaml_str.replace('---\n', ''))
        return ','.join(map(str, cleaned)) if cleaned else None
    except:
        return None

attempts_df['question_ids'] = attempts_df['question_ids'].apply(clean_to_csv)

table_name = 'attempts'
# Save to MySQL RDS
attempts_df.to_sql(
    name=table_name,          # Table name
    con=engine,               # SQLAlchemy engine
    if_exists='replace',      # Options: 'fail', 'replace', 'append'
    index=False,              # Don't write DataFrame index as a column
    chunksize=1000            # Optional: write in batches for large DataFrames
)

print(f"Transferred {len(attempts_df)} rows to {table_name} in MySQL RDS after cleaning")

attempts_df.info()

"""# 7. Quizzes Table 🟩"""

# Run query using pandas
import pandas as pd
query = "SELECT * FROM Quizzes;"  # Adjust table name if needed
df7 = pd.read_sql(query, engine)

# Preview the data
df7.head()

df7[['Quiz6', 'Quiz7', 'Quiz8']] = df7[['Quiz6', 'Quiz7', 'Quiz8']].replace('', pd.NA).fillna("Unknown")

df7.head()

# Optional: Save to a new table or CSV if needed
df7.to_sql('Quizzes', engine, index=False, if_exists='replace')

"""# 8. Cohort Enrollments 🟩"""

# Run query using pandas
import pandas as pd
query = "SELECT * FROM cohort_enrollments;"  # Adjust table name if needed
df8 = pd.read_sql(query, engine)

# Preview the data
df8.head()

# Drop metadata columns
df8.drop(columns=['_airbyte_raw_id', '_airbyte_extracted_at', '_airbyte_meta'], inplace=True)

# Preview the cleaned data
#print("Cleaned chapters data:")
#print(df4.head())
df8['created_at'] = pd.to_datetime(df8['created_at']).dt.date
df8.head()

# Optional: Save to a new table or CSV
df8.to_sql('cohort_enrollments', engine, index=False, if_exists='replace')

# OR
# df_chapters.to_csv('chapters_cleaned.csv', index=False)

df8.head()

"""# 9. Users Table 🟩"""

# Run query using pandas
import pandas as pd
query = "SELECT * FROM users;"  # Adjust table name if needed
users_df = pd.read_sql(query, engine)

# Preview the data
users_df.head()

## 1. Clean the 'role' column (remove curly braces)
users_df['role'] = users_df['role'].str.strip('{}')

## 2. Standardize email addresses (lowercase)
users_df['email'] = users_df['email'].str.lower()

import re
email_pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
valid_emails = users_df['email'].str.match(email_pattern)
users_df = users_df[valid_emails]

# Drop metadata columns
users_df.drop(columns=['_airbyte_raw_id', '_airbyte_extracted_at', '_airbyte_meta'], inplace=True)

# Preview the cleaned data
#print("Cleaned chapters data:")
#print(df4.head())

users_df.head()

# Optional: Save to a new table or CSV
users_df.to_sql('users', engine, index=False, if_exists='replace')

# OR
# df_chapters.to_csv('chapters_cleaned.csv', index=False)

users_df.head()

query = "SELECT * FROM users;"  # Adjust table name if needed
df9 = pd.read_sql(query, engine)

# Preview the data
df9.head()

"""# 10. Cohort Course Enrollments 🟩"""

# Run query using pandas
import pandas as pd
query = "SELECT * FROM cohort_course_enrollments;"  # Adjust table name if needed
df10 = pd.read_sql(query, engine)

# Preview the data
df10.head()

# Drop metadata columns
df10.drop(columns=['_airbyte_raw_id', '_airbyte_extracted_at', '_airbyte_meta'], inplace=True)

# Preview the cleaned data
#print("Cleaned chapters data:")
#print(df4.head())

df10.head()

# Optional: Save to a new table or CSV
df10.to_sql('cohort_course_enrollments', engine, index=False, if_exists='replace')

# OR
# df_chapters.to_csv('chapters_cleaned.csv', index=False)

# Preview the data
df10.head()

"""💡💡 I did not delete "exam_id" that notice in cohort_courses table 💡💡

# 11. Handin Attachments 🟩
"""

# Run query using pandas
import pandas as pd
query = "SELECT * FROM handin_attachments;"  # Adjust table name if needed
df11 = pd.read_sql(query, engine)

# Preview the data
df11.head()

# Drop metadata columns
df11.drop(columns=['_airbyte_raw_id', '_airbyte_extracted_at', '_airbyte_meta'], inplace=True)

# Preview the cleaned data
#print("Cleaned chapters data:")
#print(df4.head())

# Optional: Save to a new table or CSV
df11.to_sql('handin_attachments', engine, index=False, if_exists='replace')

# OR
# df_chapters.to_csv('chapters_cleaned.csv', index=False)

df11.head()

"""# Cohort Schedule Table 🟩"""

query = "SELECT * from Cohort_Schedule"
Cohort_Schedule_df=pd.read_sql(query, engine)

Cohort_Schedule_df.head()

# Convert start_date and end_date to datetime format
Cohort_Schedule_df['start_date'] = pd.to_datetime(Cohort_Schedule_df['start_date'], format="%d-%b-%Y", errors='coerce')
Cohort_Schedule_df['end_date'] = pd.to_datetime(Cohort_Schedule_df['end_date'], format="%d-%b-%Y", errors='coerce')

# Calculate duration in days
Cohort_Schedule_df['duration_days'] = (Cohort_Schedule_df['end_date'] - Cohort_Schedule_df['start_date']).dt.days

def clean_dependency(dep):
    if dep == 'no-dep' or 'Introduction to AI' in dep:
        return 'no-dep'
    elif '-' in dep:
        return dep.split('-', 1)[1]  # remove cohort prefix like "C01-"
    else:
        return dep

# Overwrite the column directly
Cohort_Schedule_df['dependency'] = Cohort_Schedule_df['dependency'].apply(clean_dependency)

def clean_cohort_full_info(text):
    import datetime
    import re

    match = re.match(r'^(C\d+):\s*(\d{1,2}-[A-Za-z]{3}-\d{4})~(\d{1,2}-[A-Za-z]{3}-\d{4})$', text)
    if match:
        cohort, start_str, end_str = match.groups()
        start_date = datetime.datetime.strptime(start_str, '%d-%b-%Y').strftime('%Y-%m-%d')
        end_date = datetime.datetime.strptime(end_str, '%d-%b-%Y').strftime('%Y-%m-%d')
        return f"{cohort}: {start_date} to {end_date}"  # replaced ~ with ' to '
    return text

# Apply the updated function
Cohort_Schedule_df['cohort_full_info'] = Cohort_Schedule_df['cohort_full_info'].apply(clean_cohort_full_info)
Cohort_Schedule_df['cohort_full_info'] = Cohort_Schedule_df['cohort_full_info'].str.replace('~', ' to ')

Cohort_Schedule_df.drop(columns=['start_date_dateformat', 'end_date_dateformat'], inplace=True)

Cohort_Schedule_df.head()

# Optional: Save to a new table or CSV
Cohort_Schedule_df.to_sql('Cohort_Schedule', engine, index=False, if_exists='replace')

"""# Student Status Table 🟩"""

query = "SELECT * from Student_Status"
Student_Status_df=pd.read_sql(query, engine)

Student_Status_df.head()

# Define cleaning function
def clean_target_level(value):
    if pd.isna(value) or str(value).strip() in ['', '\r']:
        return [1, 2]  # Missing or empty: treat as both levels 1 and 2
    value = str(value).strip().lower()
    if '3_only' in value or 'only_3' in value:
        return [3]
    if '+' in value:
        levels = []
        for part in value.split('+'):
            part = part.strip()
            if part.replace('.', '', 1).isdigit():
                levels.append(int(float(part)))
        return levels
    if value.replace('.', '', 1).isdigit():
        return [int(float(value))]
    return []  # Unrecognized format

# Apply the function
Student_Status_df['cleaned_levels'] = Student_Status_df['target_level'].apply(clean_target_level)

# Explode into multiple rows if there are multiple levels (e.g., "1+2")
Student_Status_df = Student_Status_df.explode('cleaned_levels')

# Drop rows with no valid level
Student_Status_df = Student_Status_df.dropna(subset=['cleaned_levels'])

# Convert to int to standardize
Student_Status_df['cleaned_levels'] = Student_Status_df['cleaned_levels'].astype(int)

# Add final cleaned label column
Student_Status_df['Target_Level'] = 'L' + Student_Status_df['cleaned_levels'].astype(str)

# drop intermediate columns if not needed
Student_Status_df = Student_Status_df.drop(columns=['target_level', 'cleaned_levels'])

# Display result
Student_Status_df.head()

# Optional: Save to a new table or CSV
Student_Status_df.to_sql('Student_Status', engine, index=False, if_exists='replace')

"""# Change Requests 🟩"""

query = "SELECT * from Change_Requests"
Change_Requests_df=pd.read_sql(query, engine)

Change_Requests_df.head()

def clean_change_requests(df):
    # Create a copy to avoid SettingWithCopyWarning
    df_clean = df.copy()

    # Trim whitespace from all string columns
    str_cols = df_clean.select_dtypes(include=['object']).columns
    df_clean[str_cols] = df_clean[str_cols].apply(lambda x: x.str.strip())

    # Rename columns to match your SQL output
    df_clean = df_clean.rename(columns={
        'name': 'Course_Name',
        'cohort_affected': 'Previous_Cohort',
        'request': 'Request_Type',
        'reschedule_to': 'Rescheduled_Cohort',
        'withdraw_reason': 'Withdrawal_Reason'
    })

    # Convert request date to datetime and format
    df_clean['request_date'] = pd.to_datetime(
        df_clean['request_date'].replace('None', pd.NA),
        format='%m/%d/%Y',
        errors='coerce'
    ).dt.strftime('%m/%d/%Y')

    # Handle special case for Stud0311
    mask = (df_clean['studentID'] == 'Stud0311') & \
           (df_clean['Previous_Cohort'].isin(['C7', 'C6'])) & \
           (df_clean['Request_Type'] == 'Need rescheduling')
    df_clean.loc[mask, 'Request_Type'] = 'Need to withdraw'

    # Clean Rescheduled_Cohort
    df_clean['Rescheduled_Cohort'] = df_clean['Rescheduled_Cohort'].replace('None', pd.NA)

    # Categorize withdrawal reasons
    conditions = [
        df_clean['Withdrawal_Reason'].str.lower().str.contains('workload|too busy', na=False),
        df_clean['Withdrawal_Reason'].str.lower().str.contains(
            'c4 conflicting with vacation|attend|requested to be pushed|assigned wrongly|'
            'skip|finish before leave|wants|in|with|part of|confirm|sick leave',
            na=False
        ),
        df_clean['Withdrawal_Reason'].str.lower().str.contains('left unit', na=False),
        (df_clean['Withdrawal_Reason'] == 'None') | df_clean['Withdrawal_Reason'].isna()
    ]

    choices = [
        'Workload',
        'Left (Other Reasons)',
        'Left Company',
        'No Reason Mentioned'
    ]

    df_clean['Withdrawal_Reason'] = np.select(conditions, choices, default='No Reason Mentioned')

    # Apply filtering
    df_clean = df_clean[
        (~df_clean['studentID'].str.contains('110')) &
        (df_clean['Request_Type'].str.lower() != 'fix wrong path')
    ]

    # Sort by studentID
    df_clean = df_clean.sort_values('studentID')

    return df_clean.reset_index(drop=True)

# Clean the dataframe
Change_Requests_df = clean_change_requests(Change_Requests_df)

# Display the cleaned data
Change_Requests_df.head()

# Optional: Save to a new table or CSV
Change_Requests_df.to_sql('Change_Requests', engine, index=False, if_exists='replace')

"""# Change New Joiners 🟩"""

query = "SELECT * from Change_New_Joiners"
Change_New_Joiners_df=pd.read_sql(query, engine)

Change_New_Joiners_df.head()

import pandas as pd

def clean_change_new_joiners(df):
    # Convert DateAdded to YYYY-MM-DD format (handling %m/%d/%Y format)
    df['DateAdded'] = pd.to_datetime(
        df['DateAdded'],
        format='%m/%d/%Y',
        errors='coerce'
    ).dt.strftime('%Y-%m-%d')

    # Clean job title - handle null/empty and convert to lowercase
    df['title'] = df['title'].where(
        df['title'].notna() & (df['title'] != ''),
        "doesn't have a job"
    ).str.lower()

    # Categorize Type
    df['Type'] = df['Type'].apply(
        lambda x: 'up: L1 to L2 or L3' if pd.notna(x) and 'L1 > L2' in x and 'L3' in x
        else 'up: L2 to L3' if pd.notna(x) and 'L2 > L3' in x
        else 'new joiner'
    )

    # Deduplicate while keeping first occurrence
    df = df.drop_duplicates(
        subset=['StudentID', 'CenterID', 'title', 'DateAdded', 'Type'],
        keep='first'
    )

    # Sort by CenterID and StudentID
    df = df.sort_values(['CenterID', 'StudentID'])

    # Reset index
    df = df.reset_index(drop=True)

    return df[['StudentID', 'CenterID', 'title', 'DateAdded', 'Type']]

# Clean the dataframe
Change_New_Joiners_df = clean_change_new_joiners(Change_New_Joiners_df)

# Display the cleaned data
print(Change_New_Joiners_df.head())

# Optional: Save to a new table or CSV
Change_New_Joiners_df.to_sql('Change_New_Joiners', engine, index=False, if_exists='replace')

"""# Cohort Assignment 🟩"""

query = "SELECT * from Cohort_Assignment"
Cohort_Assignment_df=pd.read_sql(query, engine)

Cohort_Assignment_df.head()

import pandas as pd
import numpy as np

def clean_cohort_assignment(df):
    # Make a copy to avoid SettingWithCopyWarning
    df_clean = df.copy()

    # Convert dates from '20-May-2024' format to datetime
    for date_col in ['start_date', 'end_date']:
        df_clean[date_col] = pd.to_datetime(df_clean[date_col], format='%d-%b-%Y', errors='coerce')

    # Clean text columns - trim whitespace and handle empty values
    text_cols = ['studentID', 'centerID', 'level', 'name', 'cohort',
                'cohort_status', 'withdraw_reason1', 'withdraw_reason2',
                'new_joiner', 'level_graduation_indicator']

    for col in text_cols:
        if col in df_clean.columns:
            df_clean[col] = df_clean[col].astype(str).str.strip().replace(['None', 'nan', '""', ''], np.nan)

    # Capitalize first letter of specific columns
    for col in ['cohort', 'cohort_status', 'withdraw_reason1', 'withdraw_reason2', 'new_joiner']:
        if col in df_clean.columns:
            df_clean[col] = df_clean[col].str.title()

    # Uppercase for level_graduation_indicator
    if 'level_graduation_indicator' in df_clean.columns:
        df_clean['level_graduation_indicator'] = df_clean['level_graduation_indicator'].str.upper()

    # Calculate level_status_calculated_2
    # First identify last course for each student at each level and cohort
    last_courses = df_clean.groupby(['studentID', 'level', 'cohort'])['end_date'].max().reset_index()
    last_courses = last_courses.rename(columns={'end_date': 'last_end_date'})

    # Merge with original data
    df_clean = pd.merge(df_clean, last_courses, on=['studentID', 'level', 'cohort'], how='left')

    # Calculate the new status
    conditions = [
        # Condition for status 4
        (df_clean['end_date'] == df_clean['last_end_date']) &
        (df_clean['cohort_status'].isin(['Withdraw', 'Skipped'])),

        # Condition for status 5
        (df_clean['end_date'] == df_clean['last_end_date']) &
        (df_clean['cohort_status'] == 'Completed'),

        # Condition for status 1
        df_clean['cohort_status'].isin(['Withdraw', 'Skipped']),

        # Condition for status 2
        (df_clean['cohort_status'] == 'Enrolled'),

        # Condition for status 3
        df_clean['cohort_status'].isin(['Failed', 'In-Progress', 'Completed'])
    ]

    choices = [4, 5, 1, 2, 3]

    df_clean['level_status_calculated_2'] = np.select(conditions, choices, default=np.nan)

    # Drop the temporary last_end_date column
    df_clean = df_clean.drop(columns=['last_end_date'])

    # Analysis metrics
    total_rows = len(df_clean)
    withdraw_count = len(df_clean[df_clean['cohort_status'] == 'Withdraw'])

    print(f"Total records: {total_rows}")
    print(f"Students who withdrew: {withdraw_count}")

    return df_clean

# Clean the dataframe
Cohort_Assignment_df = clean_cohort_assignment(Cohort_Assignment_df)

Cohort_Assignment_df.head()

# Optional: Save to a new table or CSV
Cohort_Assignment_df.to_sql('Cohort_Assignment', engine, index=False, if_exists='replace')

"""# materials 🟩"""

query = "SELECT * from materials"
materials_df=pd.read_sql(query, engine)

materials_df.head()

materials_df.columns

materials_df['created_at'] = pd.to_datetime(materials_df['created_at']).dt.date

# Drop metadata columns
materials_df.drop(columns=['_airbyte_raw_id', '_airbyte_extracted_at', '_airbyte_meta'], inplace=True)

materials_df['name'].unique()

materials_df['kind'].unique()

materials_df['handle'].unique()

import pandas as pd
import re
from datetime import datetime

def clean_materials_data(df):
    # Make a copy to avoid SettingWithCopyWarning
    df = df.copy()

    # 1. Clean the 'name' column - more targeted approach
    def clean_name(name):
        # Remove recording indicators and brackets
        name = re.sub(r'^\[?(Recording|Examples|Lecture|Lab|Demo|Class)\s?[-\]]?\s?', '', name, flags=re.IGNORECASE)

        # Remove parenthetical content (including dates)
        name = re.sub(r'\(.*?\)', '', name)

        # Remove specific patterns like "(Client) - " or "(Review) - "
        name = re.sub(r'^\(?(Client|Review|Call)\)?\s?[-\—]\s?', '', name, flags=re.IGNORECASE)

        # Remove standalone dates (DD-MM-YYYY or Month D, YYYY)
        name = re.sub(r'\d{2}-\d{2}-\d{4}', '', name)
        name = re.sub(r'(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]* \d{1,2},? \d{4}', '', name, flags=re.IGNORECASE)

        # Clean up remaining special characters and whitespace
        name = re.sub(r'[^\w\s-]', '', name)
        name = re.sub(r'\s+', ' ', name).strip()

        # Title case for consistency (optional)
        name = name.title()

        return name

    df['name'] = df['name'].apply(clean_name)

    # 2. Clean the 'handle' column (building on previous solution)
    def clean_handle(handle):
        # Convert to lowercase first
        handle = handle.lower()

        # Remove content in brackets and parentheses
        handle = re.sub(r'\[.*?\]', '', handle)
        handle = re.sub(r'\(.*?\)', '', handle)

        # Replace special characters with hyphens
        handle = re.sub(r'[^a-z0-9-]', '-', handle)

        # Remove multiple consecutive hyphens
        handle = re.sub(r'-+', '-', handle)

        # Remove leading/trailing hyphens
        handle = handle.strip('-')

        # Remove numeric suffixes (like '4' in 'encapsulation4')
        handle = re.sub(r'(\d+)$', '', handle)

        return handle

    df['handle'] = df['handle'].apply(clean_handle)

    # 3. Clean the 'kind' column
    kind_mapping = {
        'lab': 'lab_recording',
        'assessment': 'quiz',
        'lecture-recording': 'recording',
        'slides': 'slide'
    }
    df['kind'] = df['kind'].str.lower().replace(kind_mapping)

    return df

# Apply cleaning
materials_df = clean_materials_data(materials_df)

# أولاً تأكد من أن الأنواع متوافقة
materials_df['cohort_course_id'] = pd.to_numeric(materials_df['cohort_course_id'], errors='coerce')
cohort_courses_df['id'] = pd.to_numeric(cohort_courses_df['id'], errors='coerce')

# أنشئ القاموس من id إلى exam_id
course_id_to_exam = cohort_courses_df.set_index('id')['exam_id'].to_dict()

# عبّئ exam_id في المواد من القاموس فقط إذا كانت القيمة الأصلية مفقودة
materials_df['exam_id'] = materials_df['exam_id'].fillna(
    materials_df['cohort_course_id'].map(course_id_to_exam)
)

# Drop metadata columns
materials_df.drop(columns=['trial', 'due_date', 'duration', 'cohort_id'], inplace=True)

materials_df.head(50)

# Replace the new table after cleaning to the old one in RDS
materials_df.to_sql('materials', engine, index=False, if_exists='replace')

"""# program courses 🟩"""

query = "SELECT * from program_courses"
program_courses_df=pd.read_sql(query, engine)

program_courses_df.head()

program_courses_df.drop(columns=['_airbyte_raw_id', '_airbyte_extracted_at', '_airbyte_meta', 'resource_id'], inplace=True)

# Option 1: Using pandas merge (if working with DataFrames)
merged_df = pd.merge(
    program_courses_df,
    materials_df[['client_id', 'position']],
    on=['client_id'],
    how='left'
)

# Update position in program_courses_df
program_courses_df['position'] = merged_df['position_y'].fillna(program_courses_df['position'])

program_courses_df['created_at'] = pd.to_datetime(cohort_courses_df['created_at']).dt.date

program_courses_df.head()

# Optional: Save to a new table or CSV
program_courses_df.to_sql('program_courses', engine, index=False, if_exists='replace')

"""# programs 🟩"""

query = "SELECT * from programs"
programs_df=pd.read_sql(query, engine)

programs_df.head()

# Drop unused column
programs_df.drop(columns=['description','resource_id','free_cohort_id','organization_id','resource_id','program_category_id','_airbyte_raw_id','_airbyte_extracted_at', '_airbyte_meta'], inplace=True)

programs_df.head()

programs_df['published'] = programs_df['published'].fillna("Unknown")

# Replace the new table after cleaning to the old one in RDS
programs_df.to_sql('programs', engine, index=False, if_exists='replace')

"""# user materials 🟩"""

query = "SELECT * from user_materials"
user_materials_df=pd.read_sql(query, engine)

user_materials_df.head()

columns_to_drop = ['_airbyte_raw_id', '_airbyte_extracted_at', '_airbyte_meta']
user_materials_df = user_materials_df.drop(columns=columns_to_drop, errors='ignore')

user_materials_df.head()

columns_to_drop = ['marked_at', 'quized_at', 'quiz_results', 'grading_notes', 'grading_score', 'grading_total', 'marking_admin_id']
user_materials_df = user_materials_df.drop(columns=columns_to_drop, errors='ignore')

columns_to_drop = ['status', 'flashed', 'handin_attachment_id']
user_materials_df = user_materials_df.drop(columns=columns_to_drop, errors='ignore')

user_materials_df['user_checked'] = user_materials_df['user_checked'].fillna("Unknown")

# Optional: Save it in RDS
user_materials_df.to_sql('user_materials', engine, index=False, if_exists='replace')